### ISSUE TITLE
Help with alignment 

### ISSUE THREAD

**Issue by JordynD** [JordynD/components-on-a-grid#1]
@anna-pokhilenko

Hi Anna, I really need help! I feel like I've tried everything and I can't seem to get the figure sections to align next to each other rather than stacked. I also can't figure out how to get the logo to the bottom of the image. Any help would be greatly appreciated! Thank you!

**Comment by anna-pokhilenko** [comment]
Hello! I am attaching the screenshot of a couple adjustments I made in the code. 
<img width="351" alt="Screen Shot 2021-09-24 at 9 11 44 AM" src="https://user-images.githubusercontent.com/55008926/134680392-f62d1fd7-4f7c-4966-b7de-6723896e4cf9.png">

`main {
  display: contents;
}`

This code will help you to put your cards side by side! But don't forget to use grid-template-areas to assign the areas to the header and cards. Markbot will ask for it.
